"""Obsidian Markdown Generator — creates a rich knowledge base from Tempory Mapper JSON."""
import json
import sys
from pathlib import Path
from collections import defaultdict


def wikilink(node_id: str, label: str = None) -> str:
    """Sanitize a node ID into a safe Obsidian wikilink."""
    # Replace path separators and problematic chars
    safe = node_id.replace("/", " ").replace("\\", " ").replace("::", " ")
    safe = safe.replace("[", "").replace("]", "").replace("|", "-")
    safe = safe.replace("#", "").replace("^", "").strip()
    if label and label != safe:
        return f"[[{safe}|{label}]]"
    return f"[[{safe}]]"


def generate_obsidian_markdown(mapping_path: str, vault_dir: str = None):
    """Generate Obsidian vault from a Tempory Mapper JSON mapping.

    Args:
        mapping_path: Path to the JSON mapping file
        vault_dir: Output directory for the vault (default: obsidian_vault_<project_name>)
    """
    mapping_path = Path(mapping_path)
    with open(mapping_path, "r", encoding="utf-8") as f:
        data = json.load(f)

    metadata = data.get("metadata", {})
    project = metadata.get("project", "Unknown Project")

    if vault_dir is None:
        vault_dir = Path(f"obsidian_vault_{project}")
    else:
        vault_dir = Path(vault_dir)

    vault_dir.mkdir(parents=True, exist_ok=True)
    (vault_dir / ".obsidian").mkdir(exist_ok=True)

    nodes = {n["id"]: n for n in data["nodes"]}
    edges = data["edges"]

    # Build adjacency
    outgoing = defaultdict(list)
    incoming = defaultdict(list)
    for e in edges:
        outgoing[e["source"]].append(e)
        incoming[e["target"]].append(e)

    # Group nodes by type
    by_type = defaultdict(list)
    for nid, node in nodes.items():
        by_type[node["type"]].append(nid)

    # ── Write INDEX.md ──
    index_lines = [
        f"# {project}",
        "",
        f"> Generated by {metadata.get('generated_by', 'Tempory Mapper')} on {metadata.get('scan_date', 'unknown')}",
        "",
        "## 📊 Stats",
        f"- **Nodes:** {metadata.get('total_nodes', 0)}",
        f"- **Edges:** {metadata.get('total_edges', 0)}",
        f"- **Communities:** {metadata.get('communities_count', 0)}",
        "",
        "## 🔥 God Nodes",
        "",
        "### Internal",
    ]
    for item in metadata.get("god_nodes", {}).get("internal", []):
        n = item["node"]
        index_lines.append(f"- {wikilink(n)} ({item['degree']} connections)")

    index_lines.extend(["", "### External"])
    for item in metadata.get("god_nodes", {}).get("external", []):
        n = item["node"]
        index_lines.append(f"- {wikilink(n)} ({item['degree']} connections) [EXT]")

    index_lines.extend(["", "## 📁 By Type", ""])
    for ntype, nids in sorted(by_type.items()):
        index_lines.append(f"### {ntype.capitalize()} ({len(nids)})")
        for nid in sorted(nids):
            ext = " [EXT]" if nodes[nid].get("external") else ""
            index_lines.append(f"- {wikilink(nid)}{ext}")
        index_lines.append("")

    (vault_dir / "INDEX.md").write_text("\n".join(index_lines), encoding="utf-8")

    # ── Write per-node pages ──
    for nid, node in nodes.items():
        lines = [f"# {nid}", ""]

        # Metadata
        lines.append(f"**Type:** `{node['type']}`")
        if node.get("external"):
            lines.append("**External:** ✅")
        if node.get("community", -1) >= 0:
            lines.append(f"**Community:** {node['community']}")
        lines.append("")

        # Description if available
        # (Not in JSON currently, but future-proof)

        # Outgoing edges grouped by type
        out_edges = outgoing.get(nid, [])
        if out_edges:
            lines.append("## 📤 Outgoing")
            by_edge_type = defaultdict(list)
            for e in out_edges:
                by_edge_type[e["type"]].append(e["target"])
            for etype, targets in sorted(by_edge_type.items()):
                lines.append(f"### {etype}")
                for t in sorted(set(targets)):
                    lines.append(f"- {wikilink(t)}")
                lines.append("")

        # Incoming edges grouped by type
        in_edges = incoming.get(nid, [])
        if in_edges:
            lines.append("## 📥 Incoming")
            by_edge_type = defaultdict(list)
            for e in in_edges:
                by_edge_type[e["type"]].append(e["source"])
            for etype, sources in sorted(by_edge_type.items()):
                lines.append(f"### {etype}")
                for s in sorted(set(sources)):
                    lines.append(f"- {wikilink(s)}")
                lines.append("")

        # Community links
        comm = node.get("community", -1)
        if comm >= 0:
            comm_members = [n for n, info in nodes.items() if info.get("community") == comm and n != nid]
            if comm_members:
                lines.append("## 🏘️ Community")
                for m in sorted(comm_members)[:20]:
                    lines.append(f"- {wikilink(m)}")
                if len(comm_members) > 20:
                    lines.append(f"- ... and {len(comm_members) - 20} more")
                lines.append("")

        safe_name = nid.replace("/", "_").replace("\\", "_").replace("::", "_")
        (vault_dir / f"{safe_name}.md").write_text("\n".join(lines), encoding="utf-8")

    # ── Write file-level pages (one per source file) ──
    file_nodes = [nid for nid, n in nodes.items() if n["type"] in ("file", "router", "service", "model", "component")]
    for fid in file_nodes:
        lines = [f"# 📄 {fid}", ""]

        # Find all nodes "contained" in this file
        contained = [e["target"] for e in outgoing.get(fid, []) if e["type"] == "contains"]

        # defines: classes, functions defined in this file
        defines = [n for n in contained if nodes.get(n, {}).get("type") in ("class", "function", "method", "async_function")]
        if defines:
            lines.append("## 🏗️ Defines")
            for d in sorted(defines):
                lines.append(f"- {wikilink(d)}")
            lines.append("")

        # calls: functions this file calls
        call_targets = [e["target"] for e in outgoing.get(fid, []) if e["type"] == "calls"]
        if call_targets:
            lines.append("## 📞 Calls")
            for c in sorted(set(call_targets)):
                lines.append(f"- {wikilink(c)}")
            lines.append("")

        # imports: what this file imports
        import_targets = [e["target"] for e in outgoing.get(fid, []) if e["type"] == "imports"]
        if import_targets:
            lines.append("## 📥 Imports")
            for imp in sorted(set(import_targets)):
                lines.append(f"- {wikilink(imp)}")
            lines.append("")

        # inherits: what classes in this file inherit from
        inherit_targets = [e["target"] for e in outgoing.get(fid, []) if e["type"] == "inherits"]
        if inherit_targets:
            lines.append("## 🧬 Inherits")
            for inh in sorted(set(inherit_targets)):
                lines.append(f"- {wikilink(inh)}")
            lines.append("")

        safe_name = fid.replace("/", "_").replace("\\", "_").replace("::", "_")
        # Write as a separate page or overwrite — here we overwrite with richer content
        (vault_dir / f"{safe_name}.md").write_text("\n".join(lines), encoding="utf-8")

    # ── Write root.md ──
    root_lines = [
        f"# {project} — Root",
        "",
        f"Project root: {wikilink('root')}",
        "",
        "## Top-Level Files",
    ]
    for e in edges:
        if e["source"] == "root" and e["type"] == "contains":
            root_lines.append(f"- {wikilink(e['target'])}")
    (vault_dir / "root.md").write_text("\n".join(root_lines), encoding="utf-8")

    # ── Write .obsidian config ──
    (vault_dir / ".obsidian" / "app.json").write_text("{}")
    (vault_dir / ".obsidian" / "appearance.json").write_text("{}")

    core_plugins = {
        "graph": True,
        "backlink": True,
        "page-preview": True,
        "command-palette": True,
        "switcher": True,
        "file-explorer": True,
        "search": True,
        "tag-pane": True,
        "starred": True,
        "outline": True,
        "word-count": True
    }
    (vault_dir / ".obsidian" / "core-plugins.json").write_text(
        json.dumps(core_plugins, indent=2), encoding="utf-8"
    )

    graph_config = {
        "collapse-filter": True,
        "search": "",
        "showTags": False,
        "showAttachments": False,
        "hideUnresolved": False,
        "showOrphans": True,
        "collapse-color-groups": True,
        "colorGroups": [
            {"query": "tag:#service", "color": {"a": 1, "rgb": 16711680}},
            {"query": "tag:#router", "color": {"a": 1, "rgb": 65280}},
            {"query": "tag:#model", "color": {"a": 1, "rgb": 255}}
        ],
        "collapse-display": True,
        "showArrow": True,
        "textFadeMultiplier": 0,
        "nodeSizeMultiplier": 1,
        "lineSizeMultiplier": 1,
        "collapse-forces": True,
        "centerStrength": 0.518713248970312,
        "repelStrength": 10,
        "linkStrength": 1,
        "linkDistance": 250,
        "scale": 1
    }
    (vault_dir / ".obsidian" / "graph.json").write_text(
        json.dumps(graph_config, indent=2), encoding="utf-8"
    )

    print(f"   ✅ Vault generated: {vault_dir} ({len(nodes)} nodes)")


if __name__ == "__main__":
    if len(sys.argv) < 2:
        print("Usage: python generate_obsidian.py <mapping.json> [vault_dir]")
        sys.exit(1)

    mapping_path = sys.argv[1]
    vault_dir = sys.argv[2] if len(sys.argv) > 2 else None
    generate_obsidian_markdown(mapping_path, vault_dir)